# Anna Gerasimenko, Cholesky Decomposition Homework.

# We start with generating a random symmetric matrix

In [1]:
import numpy as np 
#need this for matrix manipulations
import time #for timing performance

## For the testing part, we will stick to matrix of integers

In [2]:
half = np.random.randint(1,10,size = (3,3)) #genera
A = half @ half.T

In [3]:
print(A)

[[ 9 19  9]
 [19 50 20]
 [ 9 20 11]]


In [4]:
n = len(A)
print(n)

3


In [5]:
#initializing empty matrix for Lower triangular
L = np.zeros((n,n))

In [6]:
print(L)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## We first will create a function that "talks" to us and explain each step it is at.

In [7]:
def cholesky_annotated(A):
    for i in range(n): 
        print(f"Row {i+1} out of {n}")
        for k in range(i+1):
            print(f"  Column {k+1} (filling {k+1}/{i+1} elements in this row)")
            sum_var = sum(L[i][j] * L[k][j] for j in range(k)) 
            
            if (i == k):
                print(f"  Diagonal element L[{i+1}][{k+1}]")
                L[i][k] = np.sqrt(A[i][i] - sum_var)
                print(f"  Value: {L[i][k]}")
            else:
                print(f"  Below-diagonal element L[{i+1}][{k+1}]")
                L[i][k] = (1/L[k][k]) * (A[i][k] - sum_var)
                print(f"  Value: {L[i][k]}")
    return L


### Let's run the function on our matrix A and see what it says to us

In [8]:
L = cholesky_annotated(A)

Row 1 out of 3
  Column 1 (filling 1/1 elements in this row)
  Diagonal element L[1][1]
  Value: 3.0
Row 2 out of 3
  Column 1 (filling 1/2 elements in this row)
  Below-diagonal element L[2][1]
  Value: 6.333333333333333
  Column 2 (filling 2/2 elements in this row)
  Diagonal element L[2][2]
  Value: 3.144660377352202
Row 3 out of 3
  Column 1 (filling 1/3 elements in this row)
  Below-diagonal element L[3][1]
  Value: 3.0
  Column 2 (filling 2/3 elements in this row)
  Below-diagonal element L[3][2]
  Value: 0.3179993640019079
  Column 3 (filling 3/3 elements in this row)
  Diagonal element L[3][3]
  Value: 1.3779972440082682


In [9]:
print(L)

[[3.         0.         0.        ]
 [6.33333333 3.14466038 0.        ]
 [3.         0.31799936 1.37799724]]


### Is this correct? Let's check by multyply L with transpose of L to see if we will get our matrix A back

In [10]:
A1 = L @ L.T

In [11]:
print(A1)

[[ 9. 19.  9.]
 [19. 50. 20.]
 [ 9. 20. 11.]]


## Let's check if we generate PD matrix A from normal distribution as told in the Homework statement

In [12]:
k = 10
half = np.random.normal(size = (k,k))
A = half @ half.T

In [13]:
def print_matrix(mat): #defining function for convenient printing of large functions
    for row in mat:
        for el in row:
            print(f"{el:.3f}", end = " ")
        print()
    

In [14]:
show1 = print_matrix(A)

11.852 -3.108 1.117 -3.760 1.019 4.386 3.588 -0.068 4.125 -1.144 
-3.108 8.780 3.445 3.342 2.706 0.073 0.077 -0.854 -0.177 -1.806 
1.117 3.445 4.103 0.559 4.559 1.179 -0.609 0.799 2.227 0.349 
-3.760 3.342 0.559 7.443 -0.078 -0.817 -2.485 -2.082 -2.459 -1.105 
1.019 2.706 4.559 -0.078 10.380 -3.651 -4.796 2.160 6.060 -1.393 
4.386 0.073 1.179 -0.817 -3.651 11.204 6.063 -2.543 0.846 -2.617 
3.588 0.077 -0.609 -2.485 -4.796 6.063 10.584 -3.202 0.693 -4.150 
-0.068 -0.854 0.799 -2.082 2.160 -2.543 -3.202 3.857 -0.037 3.632 
4.125 -0.177 2.227 -2.459 6.060 0.846 0.693 -0.037 7.212 -4.677 
-1.144 -1.806 0.349 -1.105 -1.393 -2.617 -4.150 3.632 -4.677 10.675 


In [15]:
#lets define cholesky without annotations
def cholesky(A):
    n = len(A)
    L = np.zeros((n, n))
    for i in range(n): 
         for k in range(i+1):
            sum_var = sum(L[i][j] * L[k][j] for j in range(k)) 
            
            if (i == k):
                L[i][k] = np.sqrt(A[i][i] - sum_var)
            else:
                L[i][k] = (1/L[k][k]) * (A[i][k] - sum_var)
    return L

In [16]:
L = cholesky(A)

In [17]:
show2 = print_matrix(L)

3.443 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
-0.903 2.822 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
0.325 1.324 1.498 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
-1.092 0.835 -0.129 2.353 0.000 0.000 0.000 0.000 0.000 0.000 
0.296 1.053 2.048 -0.158 2.228 0.000 0.000 0.000 0.000 0.000 
1.274 0.433 0.128 0.097 -2.124 2.204 0.000 0.000 0.000 0.000 
1.042 0.361 -0.951 -0.753 -1.641 0.585 2.205 0.000 0.000 0.000 
-0.020 -0.309 0.811 -0.740 0.320 -0.787 -0.848 1.056 0.000 0.000 
1.198 0.320 0.944 -0.551 1.503 1.046 0.755 -0.100 0.740 0.000 
-0.332 -0.746 0.965 -0.306 -1.137 -1.987 -1.610 -0.170 -0.182 1.043 


In [18]:
A1 = L@L.T
show3 = print_matrix(A1)

11.852 -3.108 1.117 -3.760 1.019 4.386 3.588 -0.068 4.125 -1.144 
-3.108 8.780 3.445 3.342 2.706 0.073 0.077 -0.854 -0.177 -1.806 
1.117 3.445 4.103 0.559 4.559 1.179 -0.609 0.799 2.227 0.349 
-3.760 3.342 0.559 7.443 -0.078 -0.817 -2.485 -2.082 -2.459 -1.105 
1.019 2.706 4.559 -0.078 10.380 -3.651 -4.796 2.160 6.060 -1.393 
4.386 0.073 1.179 -0.817 -3.651 11.204 6.063 -2.543 0.846 -2.617 
3.588 0.077 -0.609 -2.485 -4.796 6.063 10.584 -3.202 0.693 -4.150 
-0.068 -0.854 0.799 -2.082 2.160 -2.543 -3.202 3.857 -0.037 3.632 
4.125 -0.177 2.227 -2.459 6.060 0.846 0.693 -0.037 7.212 -4.677 
-1.144 -1.806 0.349 -1.105 -1.393 -2.617 -4.150 3.632 -4.677 10.675 


# Lets compare performances of my function vs np.linalg.cholesky


#### For 10X10 matrix

In [19]:
k = 10
half = np.random.normal(size = (k,k))
A = half @ half.T

In [20]:
st_t = time.time()
L = cholesky(A)
end_t = time.time()

In [21]:
st_t2 = time.time()
L1 = np.linalg.cholesky(A)
end_t2 = time.time()

In [22]:
print("Let's review the results...")
print("Given matrix A...")
print()
show4 = print_matrix(A)
print()
print("Cholesky decomposition via manual function cholesky")
print()
show5 = print_matrix(L)
print()
print("Cholesky descompostion via numpy package")
print()
show6 = print_matrix(L1)

Let's review the results...
Given matrix A...

14.760 2.168 -2.005 -0.356 3.499 2.497 0.325 3.883 0.544 -5.195 
2.168 10.409 -0.620 5.357 1.122 7.228 5.446 3.717 2.695 5.137 
-2.005 -0.620 9.273 -7.564 -1.678 -1.292 -2.212 -0.978 -1.412 1.098 
-0.356 5.357 -7.564 20.300 2.756 1.965 2.941 3.908 4.181 2.060 
3.499 1.122 -1.678 2.756 6.576 2.151 0.804 0.018 -0.355 -0.135 
2.497 7.228 -1.292 1.965 2.151 12.868 3.678 3.766 -3.374 7.081 
0.325 5.446 -2.212 2.941 0.804 3.678 7.962 -0.054 -3.017 3.956 
3.883 3.717 -0.978 3.908 0.018 3.766 -0.054 5.578 0.158 4.026 
0.544 2.695 -1.412 4.181 -0.355 -3.374 -3.017 0.158 12.229 -6.188 
-5.195 5.137 1.098 2.060 -0.135 7.081 3.956 4.026 -6.188 17.424 

Cholesky decomposition via manual function cholesky

3.842 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
0.564 3.177 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
-0.522 -0.103 2.998 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
-0.093 1.703 -2.481 3.352 0.000 0.000 0.000 0.000 0.000 0.000 
0.9

In [23]:
time_man = end_t - st_t
time_numpy = end_t2 - st_t2
print(f"Numpy took {time_numpy:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")
print(f"My function took {time_man:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")

Numpy took 0.0001931 seconds to find Cholesky decompostion of 3 X 3 matrix A
My function took 0.0003870 seconds to find Cholesky decompostion of 3 X 3 matrix A


#### For 100X100 matrices

In [24]:
k = 100
half = np.random.normal(size = (k,k))
A = half @ half.T
st_t = time.time()
L = cholesky(A)
end_t = time.time()
st_t2 = time.time()
L1 = np.linalg.cholesky(A)
end_t2 = time.time()

In [25]:
time_man = end_t - st_t
time_numpy = end_t2 - st_t2
print(f"Numpy took {time_numpy:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")
print(f"My function took {time_man:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")

Numpy took 0.0003152 seconds to find Cholesky decompostion of 3 X 3 matrix A
My function took 0.0905681 seconds to find Cholesky decompostion of 3 X 3 matrix A


#### For 1000X1000 matrices

In [26]:
k = 100
half = np.random.normal(size = (k,k))
A = half @ half.T
st_t = time.time()
L = cholesky(A)
end_t = time.time()
st_t2 = time.time()
L1 = np.linalg.cholesky(A)
end_t2 = time.time()

time_man = end_t - st_t
time_numpy = end_t2 - st_t2
print(f"Numpy took {time_numpy:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")
print(f"My function took {time_man:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")

Numpy took 0.0002692 seconds to find Cholesky decompostion of 3 X 3 matrix A
My function took 0.0878830 seconds to find Cholesky decompostion of 3 X 3 matrix A


# Part 2: Computing Determinant and Inverse

### Lets write a cofactor-expansion function to calculate the determinant of the function

In [27]:
#some thinking out loud
mat = [[1,2,3],[4,5,6],[7,8,9]]
#let's remove row 1 and column 1
#python has 0 indexing
mat1 = mat[:0]+mat[0+1:]
mat1 = [row[:0]+row[0+1:] for row in mat1]
show8 = print_matrix(mat1)

5.000 6.000 
8.000 9.000 


In [28]:
#define function for calculating matrices that are generated when ith row and jth row are removed 
def minor(mat,r,c): # r is  the row to remove and c is the column to remove
    mat = [row[:c]+row[c+1:] for row in (mat[:r]+mat[r+1:])]
    return mat

#now lets use it in the determinant function 
def determinant(mat):
    n = len(mat)
    if n == 1:
        return mat[0][0]
    det = 0 #initialize at 0
    for cofactor in range(n): #number of cofactors because we expanding along row 0 => 0+c  = c
        det += ((-1)**cofactor) * mat[0][cofactor] * determinant(minor(mat,0,cofactor))
        # mat[0][cofactor] is expanding along the first row
        # determinant(minor(mat,0,cofactor)) is recursively calling the function on all the minors
    return det

#### Is det(A) = det(L)^2?

In [29]:
k = 5
half = np.random.normal(size = (k,k))
A = half @ half.T
L = cholesky(A)

In [30]:
det1 = determinant(A.tolist()) #converting numpy array to regular python matrix
det2 = determinant(L.tolist())**2 #converting numpy array to regular python matrix
print(f"Determinant of A is {det1:.5f}")
print(f"Determinant of L squared is {det2:.5f}")

Determinant of A is 4.08632
Determinant of L squared is 4.08632


#### Is det(L) = product of digonal entries? 

In [31]:
#retrieving diagonal values of L
def diagonal(mat):
    return [mat[i][i] for i in range(len(mat))]



In [32]:
show10 = print_matrix(L)

1.846 0.000 0.000 0.000 0.000 
-0.409 1.712 0.000 0.000 0.000 
-0.427 0.115 2.541 0.000 0.000 
-0.707 -1.389 1.099 0.596 0.000 
-1.083 0.144 0.359 0.678 0.422 


In [33]:
diagonal_L = diagonal(L)
print(diagonal_L)

[np.float64(1.8462433283843553), np.float64(1.711806646586335), np.float64(2.540878445741257), np.float64(0.5962660465737513), np.float64(0.42218105700815367)]


In [34]:
print(f"The profuct of the diagonal elements is {np.prod(diagonal_L):.5f}")
print(f"The determinant of L is {determinant(L.tolist()):.5f}")

The profuct of the diagonal elements is 2.02147
The determinant of L is 2.02147


#### Therefore, we proved that determinant of L is a product of its diagonal elements.

## Part 2, b 

In [35]:
#lets define a function that inverts matrix using Cholesky decompostions
# A @ A^-1 = I 
# A = L@L.T
# A^-1 = (L^-1).T @ L^-1
def invert_via_cholesky(A):
    n = len(A)
    L = cholesky(A)
    L_inv = np.zeros((n, n)) # initializing L_inverse
    
    # Compute each column of L^(-1)
    for i in range(n):
        e_i = np.zeros(n)
        e_i[i] = 1.0
        y = np.zeros(n) # initializing 0 vector y
        
        # Solving linear equation L * y = e_i where e_i is the ith column of Identity matrix
        for j in range(n):
            y[j] = (e_i[j] - sum(L[j][k] * y[k] for k in range(j))) / L[j][j]
        
        # y is the ith column of L_inverse
        L_inv[:,i] = y
    
    A_inv = L_inv.T @ L_inv
    return A_inv

In [36]:
show10 = print_matrix(A)

3.409 -0.755 -0.789 -1.305 -1.999 
-0.755 3.098 0.372 -2.088 0.689 
-0.789 0.372 6.652 2.934 1.391 
-1.305 -2.088 2.934 3.992 1.364 
-1.999 0.689 1.391 1.364 1.959 


In [37]:
st_t = time.time()
A_inv = invert_via_cholesky(A)
end_t = time.time()

st_t2 = time.time()
A_inv2 = np.linalg.inv(A)
end_t2 = time.time()

In [38]:
print("My function Inverse reuslt")
show11 = print_matrix(A_inv)
print()
print("Numpy Inverse result")
show12 = print_matrix(A_inv2)


My function Inverse reuslt
0.936 1.156 -0.528 1.291 0.024 
1.156 8.278 -3.056 8.929 -5.777 
-0.528 -3.056 1.369 -3.449 1.965 
1.291 8.929 -3.449 10.058 -6.376 
0.024 -5.777 1.965 -6.376 5.611 

Numpy Inverse result
0.936 1.156 -0.528 1.291 0.024 
1.156 8.278 -3.056 8.929 -5.777 
-0.528 -3.056 1.369 -3.449 1.965 
1.291 8.929 -3.449 10.058 -6.376 
0.024 -5.777 1.965 -6.376 5.611 


In [39]:
time_man = end_t - st_t
time_numpy = end_t2 - st_t2
print(f"Numpy took {time_numpy:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")
print(f"My function took {time_man:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")

Numpy took 0.0001352 seconds to find Cholesky decompostion of 3 X 3 matrix A
My function took 0.0002820 seconds to find Cholesky decompostion of 3 X 3 matrix A


#### For 10x10 matrix

In [45]:
k = 10
half = np.random.normal(size = (k,k))
A = half @ half.T
print()
st_t = time.time()
A_inv = invert_via_cholesky(A)
end_t = time.time()

st_t2 = time.time()
A_inv2 = np.linalg.inv(A)
end_t2 = time.time()

time_man = end_t - st_t
time_numpy = end_t2 - st_t2
print(f"Numpy took {time_numpy:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")
print(f"My function took {time_man:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")


Numpy took 0.0001271 seconds to find Cholesky decompostion of 3 X 3 matrix A
My function took 0.0006161 seconds to find Cholesky decompostion of 3 X 3 matrix A


#### For 100x100 matrix

In [41]:
k = 100
half = np.random.normal(size = (k,k))
A = half @ half.T
# print("matrix A")
# show13 = print_matrix(A)
print()
st_t = time.time()
A_inv = invert_via_cholesky(A)
end_t = time.time()

st_t2 = time.time()
A_inv2 = np.linalg.inv(A)
end_t2 = time.time()

time_man = end_t - st_t
time_numpy = end_t2 - st_t2
print(f"Numpy took {time_numpy:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")
print(f"My function took {time_man:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")


Numpy took 0.0004380 seconds to find Cholesky decompostion of 3 X 3 matrix A
My function took 0.2790840 seconds to find Cholesky decompostion of 3 X 3 matrix A


#### For 1000X1000 matrix

In [42]:
k = 1000
half = np.random.normal(size = (k,k))
A = half @ half.T
# print("matrix A")
# show13 = print_matrix(A)
print()
st_t = time.time()
A_inv = invert_via_cholesky(A)
end_t = time.time()

st_t2 = time.time()
A_inv2 = np.linalg.inv(A)
end_t2 = time.time()

time_man = end_t - st_t
time_numpy = end_t2 - st_t2
print(f"Numpy took {time_numpy:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")
print(f"My function took {time_man:.7f} seconds to find Cholesky decompostion of {n} X {n} matrix A")


Numpy took 0.0300038 seconds to find Cholesky decompostion of 3 X 3 matrix A
My function took 279.6978359 seconds to find Cholesky decompostion of 3 X 3 matrix A


## Conclusion: My function is signficantly slower than numpy implementation